### ISSUE TITLE
🍎 iCloud3 v3.3.4.4 (1/10/2026)

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#549]
### 🐞 Bug Fixes
- **Configure > Tools**
    - Fixed a bug handling a 'No' response when confirming the action for several items
    - Fixed a bug where the results message was not displayed when the *Fix _2 Sensors Entity Name Errors* was selected. The 'fix' operation was ran correctly.
- **Sensors**:
    - Fixes the Undefined Sensors error created in v3.3.4.2
    - Reduced the time needed to create the iCloud3 sensors. Instead of recreating the master sensors list every time iCloud3 starts, it is now only recreated it when changes have been made on the Configure Sensors screen.
    - Fixed several bugs related to Excluded Sensors.
- **Apple Account** - Fixed a bug when logging into an Apple account with a blank password.
- **Internet Connection Error** - Fixed a bug handling the 1-minute timeout recheck routine after an Internet Connection Error occurred.

### 📢 Improvements
- **iCloud3 Documentation** - The iCloud3 documentation had not been reviewed and updated in a long time, probable since v3.0 or v3.1 and was due for an overhaul. It was updated and reorganized and is now, for the most part, up-to-date. The update is not complete and some items still need to be addressed. Hopefully, this will be done sometime in January, 2026. There is no question that it is better than it was. Particular attention is being paid to the _Help and Trouble Shooting Problems_ sections.

<a href="https://www.buymeacoffee.com/gcobb321" target="_blank">
<img src="https://gcobb321.github.io/icloud3_v3_docs/images/buymeacoffee-docs-button-icon.png" width="150" height="50"></a>

**Comment by C0sm0cats** [comment]
On my particular install, this seems to have broken again. All sensors show as unavailable in version v3.3.4.2.
I downgraded to v3.3.4.1.

**Comment by gcobb321** [comment]
v3.3.4.2 was a bad release that broke the sensor handling and was deleted. Install v3.3.4.4 (the heading on this issue that was just released) and you will be ok. You may have to do a *Refresh Info* on HACS to have it show up in the download list.

**Comment by C0sm0cats** [comment]
Sorry i meant All sensors show as unavailable for me also in version v3.3.4.4 , i have no issue with 3.3.4.1

**Comment by gcobb321** [comment]
Take a look at the iCloud3 docs, *Help* section. Look for the *Apple Acct, iCloud3 devices, Sensors* item. The *Sensor Issue* talks about things to try to get them back. 

If that doesn’t reset them, go to _Developer Tools > States_ and look for some of the iCloud3 sensor entity ids and see if they have a _2 (or another number suffix), like `gary_iphone_zone_distance_2`. Also look for any HA errors related to iCloud3 sensors (_Settings > System > Logs_)

**Comment by C0sm0cats** [comment]
For me, the solution was to uncheck all sensors in the iCloud configuration, restart Home Assistant, then re-check all the sensors and restart Home Assistant again. Everything came back to normal except one sensor ( battery_status) with v3.3.4.4 .

**Comment by C0sm0cats** [comment]
I understand the change:

“Instead of recreating the master sensors list every time iCloud3 starts, it is now only recreated when changes have been made on the Configure Sensors screen.”

However, there are two problems with the current behavior:

- In the Configure Sensors menu, when I uncheck sensors and click Save, they are automatically checked again. This does not seem normal and makes it impossible to actually apply changes from this screen.

- If an iCloud entity is accidentally deleted from Home Assistant, it is impossible to recreate it. Since the master sensors list is no longer recreated at startup, the deleted entity never comes back.

Previously, when iCloud3 recreated all sensors at startup, this situation was much safer: even if an entity was deleted by mistake, it would be restored automatically on restart.

With the current behavior, a simple accidental deletion can permanently break entities, with no way to recover them from the UI.

Maybe the master sensors list should still be rebuilt at startup, or there should be a reliable way to force a full sensors rebuild. 

<img width="313" height="123" alt="Image" src="https://github.com/user-attachments/assets/dc18a058-c92a-434b-abb8-72024be2459b" />

I had to roll back again to version v3.3.4.1 and then upgrade again to v3.3.4.4 to get the entity back, but it still remains unavailable.

<img width="313" height="100" alt="Image" src="https://github.com/user-attachments/assets/589881b5-cb8e-4189-83d4-ace4716c5325" />

<img width="560" height="391" alt="Image" src="https://github.com/user-attachments/assets/abfe557d-526b-4c5b-9711-6d160746e8c0" />

**Comment by gcobb321** [comment]
I will check out both situations you mentioned.  

A hash of the sensors is kept in the configuration file and the list is recreated when the hash in the config file is different than a hash calculated at startup. When a change is made to devices (one is added or delete or the name is changed) the hash in the config file is reset to force a list rebuild at startup. At least that is how it should work.

**Comment by broyuken** [comment]
iCloud3 won't load for me on this new version. HA 2026.1.0

```
Logger: homeassistant.setup
Source: setup.py:343
First occurred: 7:40:00 PM (1 occurrence)
Last logged: 7:40:00 PM

Setup failed for custom integration 'icloud3': Unable to import component: RuntimeError importing custom_components.icloud3: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/icloud3/__init__.py", line 12, in <module>
    from .utils.messaging   import (_evlog, _log, async_open_ic3log_file_init,
    ...<2 lines>...
                                    log_exception_HA, log_exception)
  File "/config/custom_components/icloud3/utils/messaging.py", line 49, in <module>
    from .utils                 import (obscure_field, instr, is_empty, isnot_empty, list_add, list_del, )
  File "/config/custom_components/icloud3/utils/utils.py", line 276, in <module>
    print(f"The hash is: {current_hash}")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/colorama/ansitowin32.py", line 177, in write
    self.write_and_convert(text)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/colorama/ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/colorama/ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
```

**Comment by C0sm0cats** [comment]
On my side,
Home Assistant Container
Core => 2026.1.0
Frontend => 20260107.0

**Comment by gcobb321** [comment]
@broyuken 
There is some code in _icloud3/utils/utils.py_ that is creating the problem. The code will never be executed but HA or Python can not load it. 

Delete lines 271-279, save the file and restart HA. 

The lines being deleted are:
```
# --- Usage Example ---
string_data = "This is some data that might change over time."

# Generate the hash
current_hash = get_string_hash(string_data)
print(f"The hash is: {current_hash}")

# This hash can now be saved to a file or database.
# When the program runs again, you can regenerate the hash and compare it.

```

**Comment by JoshBurg17** [comment]
Made the update and also the update to 2026.1 (not sure if they’re related) but now I have no sensors at all except the main diagnostic location. This is different than the previous update where all sensors showed up but stated unavailable. This time they are just not present on the device page for each phone. Tried reloading and restarting iCloud3 a few times with no success. 

Seeing this log error repeatedly as well: 

Logger: custom_components.icloud3
Source: custom_components/icloud3/utils/messaging.py:639
integration: iCloud3 v3: iDevice Tracker ([documentation](https://gcobb321.github.io/icloud3_v3_docs/#/), [issues](https://github.com/gcobb321/icloud3/issues))
First occurred: 1:34:33 PM (3 occurrences)
Last logged: 1:34:45 PM

iCloud3 Error > Error extracting device info from Apple Acct data, Device-Josh-iPhone (josh_phone), AppleAcct-*****@gmail.com. iCloudName-Josh's Phone

…update: couldn’t get any of the entities back. The integration went from 39 entities to 5. Downgraded back to v3.3.4.1 again and all the entities came back and are working once more.

**Comment by C0sm0cats** [comment]
Same. Downgraded to v3.3.4.1 again, and battery status sensor information is back.

**Comment by gcobb321** [comment]
@C0sm0cats @JoshBurg17 
This error is different than the sensor issue form before and indicates an error setting up or processing the Apple Acct data. The sensors are probably created but never updated due to the error. An _icloud3.log_ file with the _log_level_ set to `RawData` will probably show what is causing the error. 

1. Go to _Configure > Toools_ on v3.3.4.1 and set the _Log Level _to `RawData`. 
2. Reinstall v3.3.4.4 and get the errors. 
3. Edit file _icloud3/apple_acct/icloud_data_handler.py_. Remove the `# ` from the beginning of line 627 (`# log_exception(err)` to `log_exception(err)`). Be sure to remove the # and the space so everything  lines up. 
4. Restart HA 
5. Email the _icloud3.log_ file to geekstergary@gmail.com. 

That will have the Apple Acct data and the error you are getting. 


Thanks

**Comment by gcobb321** [comment]
@C0sm0cats @JoshBurg17
Another thought. After you installed v3.3.4.4, restarted and got the errors, did you review the _Event Log_ to see if there were any errors accessing or setting up the Apple account?  They would show up in Stage 3 and 4.

**Comment by C0sm0cats** [comment]
@gcobb321 I sent you icloud3.log by email (including the raw data and log_exception(err) as you suggested), along with a snapshot (everything is unavailable except the device_tracker entity). I see no errors related to accessing or setting up the Apple account in the event log.

If I downgrade to 3.3.4.1, everything works normally again. => 
<img width="318" height="535" alt="Image" src="https://github.com/user-attachments/assets/b1b0077f-02ec-48fe-abfe-0534f6c53b04" />

**Comment by gcobb321** [comment]
@C0sm0cats 
I reviewed the log file and have duplicated the problem you are having. 

**What is going on**
The `device_sensors` table in the configuration file stores the sensors to be created for each device during startup. In your case, that field is not in the configuration file so the sensors are not created. Later on in startup Stage 1, the table is built and messages are displayed in the Event Log  showing the number of sensors.
```
01-13 20:42:29 [start_ic3_co:0065]  Device Sensors List > Sensors List Rebuilt on Restart
01-13 20:42:29 [start_ic3_co:0066]  Set up Sensors > Count-47±
01-13 20:42:29 [start_ic3_co:0067]  Set up Devices > Count-1
```

I restarting HA again and all the sensors were created since the table was now initialized. This would only happen one time.

**What should happen**
iCloud3 should detect the table did not exist, create it and initialize it before the sensors are created. I will fix this in the next update.

**What you should do**
1. Install v3.3.4.4. 
2. Restart HA. 
3. Restart HA again.

**Comment by JoshBurg17** [comment]
> 3\. _icloud3/apple_acct/icloud_data_handler.py_.

Thanks Gary - I just got the logs over to you - but after following your steps to get you the logs and re-installing v3.3.4.4 it isn't reproducing the same error as before (aka it's all working now it seems?)

After we get you the logs should we go back into the file you had us edit and return it to the original state? (add back the #)

**Comment by gcobb321** [comment]
@JoshBurg17 
You do not have to add the ‘# ‘ back. What you did was to enable a log error message that is run if you get an error.  The ‘#’ makes that line a comment instead of a command that is executed

**Comment by C0sm0cats** [comment]
@gcobb321 I installed v3.3.4.4 and restarted HA twice, but unfortunately…

<img width="487" height="548" alt="Image" src="https://github.com/user-attachments/assets/af18ad27-7020-4f1e-9cf4-5f6c9449cc46" />

**Comment by gcobb321** [comment]
@C0sm0cats 
Did you try a third time? Maybe I fixed a problem but not the one you are having.

Install v3.3.4.4 again. Then unzip the _sensor v3.3.4.5.zip_ file below into the _icloud3_ directory and restart HA. This program fixes the issue I thought you had and will add a lot of debug lines to the iCloud3.log file while creating the sensors and sensor lists that might show why your sensors are not being created.

After restarting HA and getting the Unavailable errors, email the _icloud3.log_ file to geekstergary@gmail.com like you did before.

Question - What screen are you displaying in the screenshot above? Is it from the iCloud3 Integrations screen after selecting a device or another screen?

Thanks

[sensor v3.3.4.5.zip](https://github.com/user-attachments/files/24626723/sensor.v3.3.4.5.zip)

**Comment by C0sm0cats** [comment]
@gcobb321 Hi Gary,

Yes, I had already tried this three times before, but it didn’t change anything.
I followed your procedure again:
- reinstalled v3.3.4.4
- unzipped sensor v3.3.4.5.zip into the icloud3 directory (sensor.py replacement)
- restarted Home Assistant two times

I’ve sent you the logs from the two HA restarts on gcobb321 by email, and I’ve also included the screenshots.

Regarding your question, the screenshot above is from a card I added to my dashboard, but the result is the same on the iCloud3 Integration screen (via the Dashboard builder).

when I roll back to version 3.3.4.1, everything works fine again.

Thanks for your help.

**Comment by gcobb321** [comment]
When you rollback to v3.3.4.1. are you reinstalling it from HACS, doing an HA restore or something else. I’m
 asking so I know if the configuration file was also rolled back.

**Comment by C0sm0cats** [comment]
@gcobb321, i rollback to v3.3.4.1 from HACS

**Comment by gcobb321** [comment]
I looked at the log file and the sensor creation is failing creating the track_from_zone sensors for home, home2 & home3. It failed to create the sensor 'arrival_time_2' which should be 'arrival_time_home2'. I suspect it is because you are using 'home' as part of the zone name for 'home2' and 'home3'. 

There are times when the 'home' text is stripped out of full track_from_zone entity name to get the base name used to determine the sensor configuration (arrival_time_home2 --> arrival_time). But 'home' is processed before 'home2' so the base name becomes 'arrival_time_2' instead of 'arrival_time'. This would probably happen with other names also ('work', 'work2', work3', etc.).

I will compare the v3.3.4.1 code with v3.3.4.4 code in these routines to see wnat needs to be done to prevent this error and get you another _sensor.v3.3.4.5.py_ file to test.

**Comment by C0sm0cats** [comment]
@gcobb321 Thank you very much for your detailed analysis and for taking the time to track down the root cause of the issue. I really appreciate your hard work and the help you’re providing.
I’ll wait for your instructions and the sensor.v3.3.4.5.py file, and I’ll be ready to test as soon as it’s available. Thanks again for your support and excellent work.

**Comment by gcobb321** [comment]
@C0sm0cats 
I think this may have fixed everything.

[sensor v3.3.4.5.zip](https://github.com/user-attachments/files/24655600/sensor.v3.3.4.5.zip)

**Comment by C0sm0cats** [comment]
@gcobb321 
I reinstalled v3.3.4.4 from HACS
unzipped sensor v3.3.4.5.zip into the icloud3 directory (sensor.py replacement)
restarted Home Assistant and got this two Home Assistant Core logs  : 

---

Enregistreur: frontend.js.modern.202601071
Source: components/system_log/__init__.py:331
S'est produit pour la première fois: 08:47:02 (4 occurrences)
Dernier enregistrement: 08:47:11

Uncaught error from Chrome 143.0.0.0 on Linux TypeError: Cannot convert undefined or null to object iCloud3EventLogCard._getButtonDevicename (/local/icloud3/icloud3-event-log-card.js:1854:37) iCloud3EventLogCard._nameButtonPress (/local/icloud3/icloud3-event-log-card.js:1824:42) HTMLUnknownElement.<anonymous> (/local/icloud3/icloud3-event-log-card.js:976:66)

---

Enregistreur: homeassistant.setup
Source: setup.py:343
S'est produit pour la première fois: 08:46:24 (1 occurrence)
Dernier enregistrement: 08:46:24

Setup failed for custom integration 'icloud3': Unable to import component: cannot import name 'DEFAULT_DEVICE_SENSORS_CONF' from 'custom_components.icloud3.const' (/config/custom_components/icloud3/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/icloud3/__init__.py", line 21, in <module>
    from .                  import sensor as ic3_sensor
  File "/config/custom_components/icloud3/sensor.py", line 19, in <module>
    from .const             import (DOMAIN, PLATFORM_SENSOR, ICLOUD3, RARROW, NLSP4,
    ...<20 lines>...
                                    )
ImportError: cannot import name 'DEFAULT_DEVICE_SENSORS_CONF' from 'custom_components.icloud3.const' (/config/custom_components/icloud3/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/icloud3/__init__.py", line 21, in <module>
    from .                  import sensor as ic3_sensor
  File "/config/custom_components/icloud3/sensor.py", line 19, in <module>
    from .const             import (DOMAIN, PLATFORM_SENSOR, ICLOUD3, RARROW, NLSP4,
    ...<20 lines>...
                                    )
ImportError: cannot import name 'DEFAULT_DEVICE_SENSORS_CONF' from 'custom_components.icloud3.const' (/config/custom_components/icloud3/const.py)

**Comment by C0sm0cats** [comment]
@gcobb321   
I also added this tweak to the const.py file.
restarted Home Assistant
and now all is good with your last sensor.py and my tweak in const.py :)

```
# Default device sensors configuration
DEFAULT_DEVICE_SENSORS_CONF = {
    'base': {
        'track': [],
        'monitor': [],
        'track_from_zones': [],
        'excluded_sensors': [],
    }
}
```
v3.3.4.4
<img width="321" height="570" alt="Image" src="https://github.com/user-attachments/assets/0a50bbe6-812b-4f5c-a9f8-05f1f0b89dbb" />

**Comment by gcobb321** [comment]
@C0sm0cats 
I did add that to const.py and, as you found out, forgot to add it to the zip file. Thanks for figuring that out and glad everything is back to normal

**Comment by jpjupiter** [comment]
After looking at all the comments, I think I will rather not update.  After the previous break and VERY difficult roll back, mine is working with no issues on V3.3.3.1

**Comment by C0sm0cats** [comment]
@gcobb321 I'm really looking forward to v3.3.4.5 — can't wait! 😄
And please don't forget to include all the fixes and corrections we spotted together 😉

**Comment by jpjupiter** [comment]
Ok so I spoke too soon.  Now V3.3.3.1 also broke.  Why does this integration constantly lose your auth and no matter how many times you authorize and sign in, it just refuses to work.  Im at the point of just removing this integration.

**Comment by JoshBurg17** [comment]
> Ok so I spoke too soon. Now V3.3.3.1 also broke. Why does this integration constantly lose your auth and no matter how many times you authorize and sign in, it just refuses to work. Im at the point of just removing this integration.


Hey man - I wanted to start by saying that I’m sorry you’re having such issues with the integration. That really does suck. However, I just wanted to also voice that Gary has built this and given it to us for free and he works really hard to solve these issues without any compensation from all us that get to use it and integrate it into our systems. This also isn’t the place for an extended discussion - so I’ll not go on too much. If you’re frustration level has been reached, it’s totally okay to delete the integration and find another way to location track in home assistant. Just wanted to pop up to voice the side of gratitude for this integration, even if it’s not “perfect” (what ever is anyway?)

**Comment by jpjupiter** [comment]
> > Ok so I spoke too soon. Now V3.3.3.1 also broke. Why does this integration constantly lose your auth and no matter how many times you authorize and sign in, it just refuses to work. Im at the point of just removing this integration.
> 
> Hey man - I wanted to start by saying that I’m sorry you’re having such issues with the integration. That really does suck. However, I just wanted to also voice that Gary has built this and given it to us for free and he works really hard to solve these issues without any compensation from all us that get to use it and integrate it into our systems. This also isn’t the place for an extended discussion - so I’ll not go on too much. If you’re frustration level has been reached, it’s totally okay to delete the integration and find another way to location track in home assistant. Just wanted to pop up to voice the side of gratitude for this integration, even if it’s not “perfect” (what ever is anyway?)

Tsek

**Comment by gcobb321** [comment]
@jpjupiter 
Upgrade to the latest version v3.3.4.4 and a lot of your issues will probably be solved. There were problems with all applications, not just iCloud3, at the time v3.3.3.1 was released. The latest version addressed those issues.

It is available on HACS.

**Comment by broyuken** [comment]
When will 3.3.4.5 be released? Ic3 wouldn’t load for me on 3.3.4.4.

**Comment by gcobb321** [comment]
@broyuken 
I am still working on v3.3.4.5. Below is the current status and release notes.

### 🐞 Bug Fixes (Completed)
1. Fixed a bug preventing iCloud3 from loading in rare cases.
2. Fixed a bug where no sensors would be created if there were several track_from_zone sensors that started with the same name (home, home2, home3).
3. Fixed a bug preventing the iCloud3 Alerts sensor showing an Apple account needed to be authenticating from being cleared after the authentication was completed.

### 📢 Improvements (Completed)
1. _Configure > Update Apple Account_ screen - iCloud3 will now restart when an existing Apple account is logged into to ensure the account is reinitialized.
2. _Configure > Tools > Repair HA Entity Errors_ - Added the _Repair HA Entity Errors_ screen to scan the HA entity and device registries looking for iCloud3 entity errors. These errors include deleted entities (not really an error but can be cleaned up), orphaned entities (those marked as an iCloud3 entity but do not belong to the loaded version of iCloud3) and entity name errors (_2 suffix). This screen lists the errors that were found and is used to delete selected errors from the HA entity and device registries.

### 🎁 To Do before the release:
1. Remove orphaned entities and devices from the HA registries before iCloud3 creates them when starting to prevent name/unavailable entity errors.
2. Devices are maintained by iCloud3 and should not be deleted or disabled on the HA Integration screen. But if they are, entity and device name errors in the HA entity and device registry are created.

Unzip the file below into the icloud3 directory and restart HA to install a prerelease v3.3.4.5.
[icloud3 v3.3.4.5.zip](https://github.com/user-attachments/files/24971684/icloud3.v3.3.4.5.zip)

Let me know if you have any problems loading v3.3.4.5

**Comment by broyuken** [comment]
so far so good, just installed it and it at least loaded.

**Comment by C0sm0cats** [comment]
So far so good here as well 👍
Installed prerelease v3.3.4.5, it loads correctly and no issues noticed yet. Thanks! 

<img width="205" height="120" alt="Image" src="https://github.com/user-attachments/assets/43b1af9d-1657-4e44-aafb-fd005a3fd81f" />
