### ISSUE TITLE
unexpected keyword argument 'retry_cnt' on iCloud3 3.3

### ISSUE THREAD

**Issue by marceloaf** [gcobb321/icloud3#527]
Hi Gary, thanks for this release!

I noticed the error below after installing 3.3. Not sure if it’s worth mentioning I’m still in HA 2025.10.3.

Logger: custom_components.icloud3
Source: custom_components/icloud3/apple_acct/icloud_session.py:376
integration: iCloud3 v3: iDevice Tracker ([documentation](https://gcobb321.github.io/icloud3_v3_docs/#/), [issues](https://github.com/gcobb321/icloud3/issues))
First occurred: 17:13:18 (5 occurrences)
Last logged: 20:10:56

iCloudSession.request() got an unexpected keyword argument 'retry_cnt'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/apple_acct/icloud_session.py", line 376, in _request
    return self.request(method, url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: iCloudSession.request() got an unexpected keyword argument 'retry_cnt'

**Comment by gcobb321** [comment]
Thanks. I remember seeing that but it then went away so I forgot about it. It has to do with retrying an Apple data request that failed on the first time. Rare but fixable.

**Comment by JoshBurg17** [comment]
I'm getting this error as well with what I think is every location update (6 occurrences over the last 3 hours). Is there something we do on our end to fix this?

**Comment by edautz** [comment]
Same problem right after the upgrade tot version 3.3. Running HA 2025.7.2

**Comment by Destroyer061090** [comment]
Same issue with actual HA 2025.11.2

Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.icloud3
Fonte: custom_components/icloud3/apple_acct/icloud_session.py:376
Integrazione: iCloud3 v3 (documentazione, problemi)
Prima occorrenza: 15 novembre 2025 alle ore 23:54:28 (26 occorrenze)
Ultimo accesso: 12:59:29

iCloudSession.request() got an unexpected keyword argument 'retry_cnt'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/apple_acct/icloud_session.py", line 376, in _request
    return self.request(method, url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: iCloudSession.request() got an unexpected keyword argument 'retry_cnt'

**Comment by edautz** [comment]
After upgrading to 3.3.1 problem resolved. Gary thank you for swift action and neverending support.

**Comment by JoshBurg17** [comment]
Same - error all gone after updating to 3.3.1! Thank you so much Gary!! You really are a wonderful human.
