### ISSUE TITLE
Lost iphone service does not work

### ISSUE THREAD

**Issue by starostin** [gcobb321/icloud3#39]
Hi, thanks a lot for this component. 
I have tried to call device_tracker.icloud_lost_iphone service, but got an error:

```
 [homeassistant.components.websocket_api.http.connection.140319335894656] 'NoneType' object has no attribute 'play_sound'
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/app/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/app/homeassistant/core.py", line 1162, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/icloud3/device_tracker.py", line 392, in service_callback_lost_iphone
    devicename)
  File "/config/custom_components/icloud3/device_tracker.py", line 4512, in service_handler_lost_iphone
    device.play_sound()
AttributeError: 'NoneType' object has no attribute 'play_sound'
```

Thanks in advance

**Comment by asifma** [comment]
Same here...

**Comment by gcobb321** [comment]
**@starostin , @asifma**  This error means the devicename that is setup in the script or automation is not one of the devices being tracked by iCloud3. Either the devicename is misspelled in the automation or script calling the lost_phone service call or it did not pass one of the include/exclude filters when iCloud3 started. If you have the 'device_tracker.devicename' displayed on the lovelace screen, click it and the 'tracking' attribute is towards the end of the list. 

The script to find my phone is:
```icloud_lost_iphone_gary:
  alias: 'Find Lost Phone Alert (Gary)'
  sequence:
    - service: device_tracker.icloud_lost_iphone
      data:
        device_name:  gary_iphone
 ```
```tracking         gary_iphone, lillian_iphon``` 
(Note: The last character of the devicename is cut off).

**Comment by starostin** [comment]
Hi, thanks for your response. I have investigated also a bit this issue. So, the problem that I use this components 3 times for 3 accounts, and when I logged tracked devices - I see just device from the last account. That is why my device can't be found. Or something wrong with my settings? For all components I have filter include_device

**Comment by gcobb321** [comment]
I set up my test environment using separate accounts for my phone and my wife's phone. My phone issued the Lost Phone Alert but my wife's did not. So there is definitely something that I will look into.

I am going out of town for the next two weeks and do not want to put new code on Github as I walk out the door. I'll look into the problem and will send you a copy if I get it fixed. before then. Send me your email address at geekstergary@gmail.com and I will let you know if I get the error corrected before I leave.

Gary

**Comment by gcobb321** [comment]
Attached is the file for iCloud v1.0.4.

Version 1.0.4  Change Log
=================
- Fixed problem where iCloud Service Calls may not be executed for a 
device when multiple iCloud3 device tracker platforms were set up for 
different iCloud accounts.
- Fixed a problem where the last update, the next update and last 
located dates were displayed as a UTC time rather than the local time. 
This has been fixed. It appears that newer installs of Hass.io that are 
based on the Hass.io Operating System rather than Raspbian are using UTC 
for log file times rather than the local time. This was effecting the 
how times are used and reported.
- Fixed a problem where the Old Location count was being updated twice 
on the same poll.
- If a device has an old location, it was repolled every 15-seconds to 
try to establish a good location. This has been changed to 30-seconds. 
Every 10th time, the interval will be set to 5-minutes. If the the Old 
Location counter reaches 41or the last good location is more than 
30-minutes old and the Old Location counter reaches 21, the device is 
put into a 'Paused' status and no more polling will be done until it is 
resumed using the 'icloud_update resume' service call. This might happen 
in large dead zone or when a device is put into 'airplane' mode with no 
wifi coverage.
- Began preparations for version 2 of the IOS App.


Let me know if you have any problems (or if you don't have any problems) 
so I can fix them before releasing this version

Gary Cobb

------ Original Message ------

**Comment by starostin** [comment]
Hi. I have just tried your code, and HA is not working when I use it. 
```


----------------------------------------


Exception happened during processing of request from ('192.168.1.234', 53536)


Traceback (most recent call last):


  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread


    self.finish_request(request, client_address)


  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request


    self.RequestHandlerClass(request, client_address, self)


  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__


    self.handle()


  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle


    self.handle_one_request()


  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request


    method()


  File "/usr/local/lib/python3.7/site-packages/pysonos/events.py", line 269, in do_NOTIFY


    subscription.events.put(event)


  File "/usr/src/app/homeassistant/components/sonos/media_player.py", line 173, in put


    self._handler(item)


  File "/usr/src/app/homeassistant/components/sonos/media_player.py", line 590, in update_volume


    self.schedule_update_ha_state()


  File "/usr/src/app/homeassistant/helpers/entity.py", line 336, in schedule_update_ha_state


    self.hass.add_job(self.async_update_ha_state(force_refresh))


  File "/usr/src/app/homeassistant/core.py", line 246, in add_job


    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)


  File "uvloop/loop.pyx", line 1261, in uvloop.loop.Loop.call_soon_threadsafe


  File "uvloop/loop.pyx", line 604, in uvloop.loop.Loop._call_soon


  File "uvloop/loop.pyx", line 608, in uvloop.loop.Loop._call_soon_handle


  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed


RuntimeError: Event loop is closed


----------------------------------------
```

**Comment by gcobb321** [comment]
It looks like the code I sent was embedded in the email rather than attached as a separate file. I have uploaded v1.0.4b to the gethub site. It can be found [here](https://github.com/gcobb321/icloud3/blob/master/prerelease/device_tracker.py).

I didn't see the custom_omponent.device_tracker.icloud3 in any of the errors killing ha, only media_player.py. Try the code on github and see what happens.

**Comment by starostin** [comment]
Should it work in HA 0.94? Because I have just updated to this version.

**Comment by gcobb321** [comment]
I just updated to 0.94.0 and icloud3 doesn't load on my system either. The ha log file just says device_tracker.icloud3 not found. I was just getting ready to look into it and see what is going on. I'll post some info once I see what has to be done,

**Comment by starostin** [comment]
Great! Thanks

**Comment by riemers** [comment]
Yeah, same here. Doesn't work anymore. Sadly my templates that read out values from these sensor break because of this. (didn't know that, so speech is broken since it cannot talk the sensor sort of speak)

**Comment by gcobb321** [comment]
The code that was suppose to fix this never made it into the final update. I've updated iCloud3 to v1.0.4a and it can be found in the iCloud3 repository in the prerelease directory [here](https://github.com/gcobb321/icloud3/tree/master/prerelease). Let me know if you have any further issues.

**Comment by riemers** [comment]
Seems to be working just fine. Had to authorize again, but that was it. Small note, i could not find if you have to restart icloud3 after you did the authorisation or not. Since it didn't change for me i just called the service icloud3 restart and then it became active.

**Comment by starostin** [comment]
Hi. I have just tried new version. I have some errors:
```
Wed Jun 12 2019 15:17:55 GMT+0300 (Eastern European Summer Time)
'Icloud' object has no attribute 'any_device_being_updated_flag'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 1219, in _polling_loop_5_sec_device
    if self.any_device_being_updated_flag:
AttributeError: 'Icloud' object has no attribute 'any_device_being_updated_flag'
```


```
Wed Jun 12 2019 15:16:55 GMT+0300 (Eastern European Summer Time)
Error setting up platform legacy
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/device_tracker/setup.py", line 76, in async_setup_legacy
    tracker.see, discovery_info)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/icloud3/device_tracker.py", line 411, in setup_scanner
    self._LOGGER_error_msg(log_msg)
NameError: name 'self' is not defined
```


I also have error about invalid credentials, but seems it is not related to this component 
```
Error logging into iCloud Service: ('Invalid email/password combination.', PyiCloudAPIResponseError('Failed to validate the credentials from cookie'))
```

**Comment by gcobb321** [comment]
Fixed in v1.0.5
