### ISSUE TITLE
iiCloud3 v3.5 - Questions, Problems & Comments

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#582]
iCloud3 v3.5 - Questions, Problems & Comments

**Comment by kurim** [comment]
Currently Auth requiere disable IPv6, which will break Matter since it require IPv6.
Can IPv6 re-enable, after Auth?
If not, what can be a possible solution to use both?

**Comment by gcobb321** [comment]
@kurim 
iCloud3 v3.5 always uses IPv4 for the auth process. It will not cause problems if IPv6 is enabled, so you can enable IPv6 and leave it enabled.

**Comment by Aurel004** [comment]
Hi, I tried a first install of 3.5, but when I clicked the gear icon, I've got this error

```
Enregistreur: aiohttp.server
Source: /usr/local/lib/python3.14/site-packages/aiohttp/web_protocol.py:488
S'est produit pour la première fois: 12:42:07 (1 occurrence)
Dernier enregistrement: 12:42:07
Error handling request from 172.30.33.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/aiohttp/web_protocol.py", line 517, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 214, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 90, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 263, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 89, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 291, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 121, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 336, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 383, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 483, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/configure/screens/step_tools.py", line 374, in async_step_restart_ha
    return await self.async_step_menu()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/config_flow.py", line 638, in async_step_menu
    self._set_inactive_devices_header_msg()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/icloud3/configure/screens/step_icloud3_device.py", line 1102, in _set_inactive_devices_header_msg
    if instr(self.data_source, ICLOUD):
             ^^^^^^^^^^^^^^^^
AttributeError: 'iCloud3_OptionsFlowHandler' object has no attribute 'data_source'. Did you mean: '_set_data_source'? 
```

Got it working using v3.4.3.1

But now I'm having an other issue (v3.4.3.1 and v5):
I added my apple account, seems to work, I added a new iDevice, saved, and restarted iCloud3 + HA but when it restarts, the Apple account doesn't appear in "accounts" anymore, even if I can not add it one more time as it knows it's already been added (but cannot delete it)

What I see in logs:
```
This error originated from a custom integration.

Enregistreur: custom_components.icloud3
Source: custom_components/icloud3/utils/messaging.py:642
intégration: iCloud3 v3 (documentation, problèmes)
S'est produit pour la première fois: 16:28:26 (1 occurrence)
Dernier enregistrement: 16:28:26

iCloud3 Device Configuration Error > iPhone Aurel iCloud3 (iphone_daurel_icloud3), Unknown Apple Acct (XXX**2**XX@)
```
(btw there is no "2" in my email, might be the dot `.` ?)

**Comment by gcobb321** [comment]
So are you running v3.5 or v3.4.3?
The 2 in the middle of the name is just part of the Apple acct email display to hide the actual name. 
Go to the _Configure > Apple Account_ screen and check the Apple accounts listed. You might have to delete and readd them.

**Comment by Aurel004** [comment]
I tried on both v3.4.3.1 and v3.5

The account configured does not appear in the list

<img width="693" height="784" alt="Image" src="https://github.com/user-attachments/assets/254c3444-7121-4694-ac21-14bae2c21659" />

But as you can see, it knows there is one by the message "Warning: Apple Accts have been set up but are not used as a data source"

In iCloud3 Devices, it is like this

<img width="415" height="35" alt="Image" src="https://github.com/user-attachments/assets/56ed6b1d-10cd-40e0-9074-cf763b180223" />

**Comment by gcobb321** [comment]
See the checkbox ‘Requesr Location data from devices in the Apple account’. It is unchecked meaning the Apple account will not be used. Check it t to enable account data. See screen from the iCloud3 docs below

There are some heading fields that are not filled in correctly (data_source_mobapp & _apple_acct). That indicates something is missing from one of the v3.5 files. First reinstall v3.5 from HACS. Check the 3-dots on the right side on the iCloud3 line. Then select Update Info, then Redownload, then restart HA. 

<img width="2420" height="1668" alt="Image" src="https://github.com/user-attachments/assets/93d7f358-2b9e-4fa3-aa5c-64f520b80b1e" />

**Comment by Aurel004** [comment]
Thank you, I thought "Family Sharing List" was to get other devices

> There are some heading fields that are not filled in correctly (data_source_mobapp & _apple_acct). That indicates something is missing from one of the v3.5 files. First reinstall v3.5 from HACS. Check the 3-dots on the right side on the iCloud3 line. Then select Update Info, then Redownload, then restart HA.

It did the trick thanks.

**Comment by MarcDBehr** [comment]
Found this in the logs after a HA restart (icloud version 3.5.1)

2026-05-14 06:18:56.011 ERROR (SyncWorker_3) [custom_components.icloud3] 'from_zone'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/startup/restore_state.py", line 121, in read_icloud3_restore_state_file
    from_zones = devicename_data['from_zone']
                 ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'from_zone'
2026-05-14 06:18:56.041 ERROR (SyncWorker_3) [custom_components.icloud3] 'from_zone'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/startup/restore_state.py", line 121, in read_icloud3_restore_state_file
    from_zones = devicename_data['from_zone']
                 ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'from_zone'
2026-05-14 06:18:56.816 ERROR (SyncWorker_3) [custom_components.icloud3] 'from_zone'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/startup/start_ic3.py", line 1220, in create_Devices_object
    Device = iCloud3_Device(devicename, conf_device)
  File "/config/custom_components/icloud3/device.py", line 136, in __init__
    self.initialize_sensors()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/icloud3/device.py", line 405, in initialize_sensors
    for zone in Gb.restore_state_devices[self.devicename]['from_zone']:
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^

**Comment by Aurel004** [comment]
Hi,

1. I've a "known" zone where I am in (it is not Home), but iCloud3 created a StatZone and is saying I'm in the StatZone, not in the known zone. I was wondering why and how to remove it ?

<img width="809" height="641" alt="Image" src="https://github.com/user-attachments/assets/5783d43e-8f3c-4df2-a8d4-2ff6d595ba61" />


2. Waze travel time doesn't seem to work from Switzerland ? It works for one device in the same country as the Home Zone, but for a device in an other country, the logs say this

<img width="390" height="80" alt="Image" src="https://github.com/user-attachments/assets/91edb435-1922-4b2b-95d8-bfe6777504f2" />

**Comment by gcobb321** [comment]
@Aurel004 
1. The gps accuracy may be poor so the location received from Apple puts the phone outside of “your zone” and a star zone is created. It will be deleted automatically after you move out of it. You may want to set the size of your zone to 100m. 
2. The error message says that device can not connect to Waze. That means an error was encountered getting data back from Waze using your Internet connection. I can not help you on that error. Restarting the device may help.

**Comment by Aurel004** [comment]
@gcobb321 
1. I checked and the location received from Apple is good
I moved out the zone, it got deleted, but as soon as I come back in the zone, I've got the StatZone recreated inside the known zone
(I did extend the radius of the zone but same result)

2. Oh okay, didn't know it was done device-side

**Comment by gcobb321** [comment]
Restart iCloud3 (_Event Log > Actions > Restart iCloud3_) to clear everything up and see it continues. This will clear all internal tables, including the StatZones. 

iCloud3 keeps the StatZones internally for a little while in case they are needed by another device and then deletes them. Also, zone add/delete should be picked up by iCloud3 when they happen but size changes may not be. A restart will refresh everything.

**Comment by Aurel004** [comment]
Restarting iCloud3 did not seem to clear the StatZone

But, I remembered that the known zone was set as "Passive" (=only for automations). I think iCloud3 does not like passive zones so I switched off to make it "Active" and it seems to work well now!

**Comment by gcobb321** [comment]
Ahh, you are correct about a passive zone. iCloud3 treats it as an inactive zone and does n not load it into its internal tables. Glad you figured that out. Happy Tracking.
